import { useEffect, useMemo, useRef, useState } from 'react';
import { portfolioProjects } from '../data/projects.js';

const STATE_KEY='kdk-project-bones-v2';
const initialGame=()=>{try{return {...{collected:[],unlockedProjects:[],x:24,y:150},...JSON.parse(localStorage.getItem(STATE_KEY)||'{}')}}catch{return {collected:[],unlockedProjects:[],x:24,y:150}}};

function ProjectGrid({game,setGame}){
  const wallet=Math.max(0,game.collected.length-game.unlockedProjects.length);
  const unlock=slug=>{if(!wallet||game.unlockedProjects.includes(slug))return;setGame(value=>({...value,unlockedProjects:[...value.unlockedProjects,slug]}));};
  return <div className="project-grid" id="project-grid">{portfolioProjects.map(project=>{const locked=project.requiresUnlock&&!game.unlockedProjects.includes(project.slug);return <article key={project.slug} className={`project-card${locked?' is-locked':''}`} data-status={project.status} data-slug={project.slug}><div className="project-media">{project.thumbnail?<img src={project.thumbnail} alt={`${project.title} 프로젝트 미리보기`} width="800" height="450"/>:<div className="project-placeholder">PROJECT SLOT</div>}</div><div className="project-body"><span className="project-category">{project.category} · {project.period}</span><h3>{project.title}</h3><p>{project.description}</p><div className="project-tags">{project.tags.map(tag=><span key={tag}>{tag}</span>)}</div></div>{locked?<button className="project-lock" type="button" data-unlock={project.slug} disabled={!wallet} onClick={()=>unlock(project.slug)}>{wallet?'🦴 1개로 해금':'🦴 뼈가 필요해요'}</button>:project.status==='coming-soon'?<span className="project-lock">COMING SOON</span>:<a className="project-link" href={project.href} aria-label={`${project.title} 상세 페이지 보기`}/>}</article>})}</div>;
}

function CursorMongi(){
  const followerRef=useRef(null); const target=useRef({x:innerWidth/2,y:innerHeight/2}); const current=useRef({...target.current}); const raf=useRef(0); const timers=useRef([]); const [visible,setVisible]=useState(false); const [state,setState]=useState('walk');
  useEffect(()=>{if(!matchMedia('(pointer:fine)').matches)return;const animate=()=>{const node=followerRef.current;if(!node)return;current.current.x+=(target.current.x-current.current.x)*.18;current.current.y+=(target.current.y-current.current.y)*.18;const flip=target.current.x<current.current.x?-1:1;node.style.transform=`translate3d(${current.current.x}px,${current.current.y}px,0) scaleX(${flip})`;raf.current=Math.abs(target.current.x-current.current.x)+Math.abs(target.current.y-current.current.y)>.35?requestAnimationFrame(animate):0};const clearTimers=()=>{timers.current.forEach(clearTimeout);timers.current=[]};const move=event=>{if(event.pointerType!=='mouse')return;target.current={x:Math.max(8,Math.min(innerWidth-82,event.clientX+12)),y:Math.max(8,Math.min(innerHeight-82,event.clientY+14))};setVisible(true);setState('walk');clearTimers();timers.current=[setTimeout(()=>setState('stand'),140),setTimeout(()=>setState('sit'),1500),setTimeout(()=>setState('sleep'),5000)];if(!raf.current)raf.current=requestAnimationFrame(animate)};addEventListener('pointermove',move,{passive:true});return()=>{removeEventListener('pointermove',move);clearTimers();cancelAnimationFrame(raf.current)}},[]);
  return <div ref={followerRef} className={`cursor-mongi${visible?' show':''}`} data-state={state} aria-hidden="true"/>;
}

function BoneGame({game,setGame}){
  const arenaRef=useRef(null); const mungiRef=useRef(null); const boneRefs=useRef([]); const active=useRef(new Set()); const frame=useRef(0); const [motion,setMotion]=useState('stand'); const [direction,setDirection]=useState('front'); const [message,setMessage]=useState(''); const complete=game.collected.length===3; const wallet=Math.max(0,game.collected.length-game.unlockedProjects.length); const positions=[[18,23],[52,78],[81,39]];
  useEffect(()=>{localStorage.setItem(STATE_KEY,JSON.stringify(game));},[game]);
  useEffect(()=>{let sit,sleep;if(!complete&&!active.current.size){sit=setTimeout(()=>setMotion('sit'),1100);sleep=setTimeout(()=>setMotion('sleep'),4300)}return()=>{clearTimeout(sit);clearTimeout(sleep)}},[game.x,game.y,complete]);
  useEffect(()=>{const keys={ArrowUp:'up',ArrowDown:'down',ArrowLeft:'left',ArrowRight:'right',KeyW:'up',KeyS:'down',KeyA:'left',KeyD:'right'};let last=performance.now();const loop=time=>{const scale=Math.min((time-last)/16.67,2);last=time;if(active.current.size&&!complete){const dx=Number(active.current.has('right'))-Number(active.current.has('left'));const dy=Number(active.current.has('down'))-Number(active.current.has('up'));const length=Math.hypot(dx,dy)||1;setGame(value=>{const arena=arenaRef.current;return {...value,x:Math.max(0,Math.min(value.x+dx/length*5.4*scale,(arena?.clientWidth||400)-72)),y:Math.max(0,Math.min(value.y+dy/length*5.4*scale,(arena?.clientHeight||320)-72))}});setMotion('walk');setDirection(dy<0?'back':dy>0?'front':dx<0?'left':'right');frame.current=requestAnimationFrame(loop)}else frame.current=0};const down=e=>{const dir=keys[e.code];if(!dir||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;e.preventDefault();active.current.add(dir);setMotion('walk');if(!frame.current){last=performance.now();frame.current=requestAnimationFrame(loop)}};const up=e=>{const dir=keys[e.code];if(dir){active.current.delete(dir);setMotion('stand');setGame(v=>({...v}));setTimeout(()=>{if(!active.current.size)setMotion('sit')},1000);setTimeout(()=>{if(!active.current.size)setMotion('sleep')},4200)}};addEventListener('keydown',down);addEventListener('keyup',up);return()=>{removeEventListener('keydown',down);removeEventListener('keyup',up);cancelAnimationFrame(frame.current)}},[complete,setGame]);
  useEffect(()=>{if(complete||!mungiRef.current)return;const dog=mungiRef.current.getBoundingClientRect();boneRefs.current.forEach((bone,index)=>{if(!bone||game.collected.includes(index))return;const target=bone.getBoundingClientRect();const overlaps=dog.left<target.right&&dog.right>target.left&&dog.top<target.bottom&&dog.bottom>target.top;if(!overlaps)return;setGame(value=>value.collected.includes(index)?value:{...value,collected:[...value.collected,index]});setMessage('뼈다귀 획득! '+Math.min(game.collected.length+1,3)+'/3')});},[game.x,game.y,game.collected,complete,setGame]);
  const quick=()=>{setGame(value=>({...value,collected:[0,1,2]}));setMessage('뼈 3개를 받았습니다. 프로젝트를 선택하세요.')}; const reset=()=>{localStorage.removeItem(STATE_KEY);setGame({collected:[],unlockedProjects:[],x:24,y:150});setMotion('stand')}; const move=dir=>{const delta={up:[0,-18],down:[0,18],left:[-18,0],right:[18,0]}[dir];setDirection(dir==='up'?'back':dir==='down'?'front':dir);setMotion('walk');setGame(v=>({...v,x:Math.max(0,v.x+delta[0]),y:Math.max(0,v.y+delta[1])}));setTimeout(()=>setMotion('stand'),180)};
  return <section className="game-shell" aria-labelledby="game-title"><div className="game-head"><div><h2 id="game-title">몽이의 프로젝트 탐험</h2><p>뼈 1개로 프로젝트 1개를 해금하고, 3개를 모두 찾으면 몽이가 따라옵니다.</p></div><div className="game-meta"><output id="bone-count" aria-live="polite">{wallet}개 보유 · {game.collected.length}/3 수집</output><div className="game-actions"><button id="quick-unlock" type="button" onClick={quick}>뼈 바로 받기</button><button id="game-reset" type="button" onClick={reset}>초기화</button></div></div></div><div className="mobile-game-guide"><span>1. 몽이를 움직여 뼈를 찾으세요.</span><span>2. 뼈 1개로 프로젝트 1개를 열 수 있어요.</span></div><div className="game-arena" id="game-arena" ref={arenaRef} tabIndex="0" role="application" aria-label={complete?'미니게임 완료. 뼈다귀로 프로젝트를 해금할 수 있습니다.':'방향키로 몽이를 움직여 뼈다귀 세 개를 모으는 게임'}><span className="scenery cloud one"/><span className="scenery cloud two"/><span className="scenery tree one"/><span className="scenery tree two"/><span className="scenery path"/><span className="game-zone">MONGI PARK · BONE QUEST</span><div className="mungi" id="mungi" ref={mungiRef} data-direction={direction} data-motion={motion} role="img" aria-label="몽이 캐릭터" style={{left:game.x,top:game.y,visibility:complete?'hidden':'visible'}}/>{positions.map(([left,top],index)=>!game.collected.includes(index)&&<button key={index} className="bone" ref={node=>{boneRefs.current[index]=node}} type="button" aria-label={`${index+1}번째 뼈다귀`} style={{left:`calc(${left}% - 21px)`,top:`calc(${top}% - 21px)`}} onClick={()=>setGame(v=>({...v,collected:[...new Set([...v.collected,index])]}))}>🦴</button>)}<output className={`game-message${message?' show':''}`} id="game-message" aria-live="polite">{message}</output><span className="game-help">게임을 클릭한 뒤 ← ↑ ↓ → 이동</span><div className="dpad" aria-label="몽이 이동 버튼">{[['up','↑','위로'],['left','←','왼쪽으로'],['down','↓','아래로'],['right','→','오른쪽으로']].map(([dir,label,aria])=><button key={dir} type="button" data-move={dir} aria-label={aria} onClick={()=>move(dir)}>{label}</button>)}</div></div>{complete&&<CursorMongi/>}</section>;
}

export default function HomePage(){const [game,setGame]=useState(initialGame);const [heroVisible,setHeroVisible]=useState(false);const [profileVisible,setProfileVisible]=useState(false);const profileRef=useRef(null);useEffect(()=>{let cancelled=false;const show=async()=>{await document.fonts.ready;requestAnimationFrame(()=>requestAnimationFrame(()=>{if(!cancelled)setHeroVisible(true)}))};show();return()=>{cancelled=true}},[]);useEffect(()=>{const observer=new IntersectionObserver(([entry])=>setProfileVisible(entry.isIntersecting),{threshold:0});if(profileRef.current)observer.observe(profileRef.current);return()=>observer.disconnect()},[]);return <main id="main"><section className="hero wrap" id="top"><div className="hero-grid"><div className={`motion-ready${heroVisible?' is-visible':''}`}><p className="eyebrow">〈 WEB PUBLISHER · PORTFOLIO 〉</p><h1 className="display"><span className="display-kicker">균형 잡힌 인재</span><span className="display-name-line"><span className="display-name">강동균</span><span className="display-suffix">입니다.</span></span></h1><p className="hero-desc">콘텐츠 구조를 설계하고 반응형 인터페이스와 재사용 가능한 규칙으로 구현합니다.</p><div className="hero-actions"><a className="pill dark" href="#projects">프로젝트 보기</a><a className="pill" href={`mailto:${'dongkyunpeter@gmail.com'}`}>이메일 보내기</a></div></div><BoneGame game={game} setGame={setGame}/></div></section><section ref={profileRef} className={`profile${profileVisible?' is-visible':''}`} id="profile"><div className="wrap profile-card"><div className="profile-copy"><p className="eyebrow">〈 ABOUT ME 〉</p><h2 className="profile-name">강동균</h2><p>디자인 의도를 구조와 동작으로 번역하고,<br/>구현 이후의 반응형·접근성·성능까지 직접 검증합니다.</p><ul className="profile-list"><li><strong>LEVEL</strong><span>신입 웹 퍼블리셔</span></li><li><strong>ROLE</strong><span>Web Publishing · UI Implementation</span></li><li><strong>STACK</strong><span>React · CSS · JavaScript</span></li><li><strong>FOCUS</strong><span>Design System · Accessibility · Performance</span></li></ul><div className="profile-contact"><a className="pill dark" href="mailto:dongkyunpeter@gmail.com">이메일 보내기</a><a className="pill" href="https://github.com/dongkyunpeter-alt/kdk_portfolio" target="_blank" rel="noreferrer">GitHub ↗</a></div></div></div></section><section className="projects" id="projects"><div className="wrap"><div className="section-head"><div><p className="eyebrow">〈 SELECTED PROJECTS 〉</p><h2>Projects</h2></div></div><ProjectGrid game={game} setGame={setGame}/></div></section></main>}
