import WorkCarousel from '../components/WorkCarousel.jsx';
import { portfolioProjects } from '../data/projects.js';

const pulmuoneProject=portfolioProjects.find(project=>project.slug==='pulmuone');

export default function PulmuonePage(){return (
<main id="main">
  <section className="hero wrap" aria-labelledby="hero-title">
    <div className="hero-layout"><div className="hero-copy reveal">
        <p className="eyebrow">〈 WEB PUBLISHER · PORTFOLIO 〉</p>
        <h1 className="display" id="hero-title">풀무원과<br />바른먹거리를<br />하나의 경험으로</h1>
      </div></div>
  </section>
  <WorkCarousel />
  <section className="intro wrap reveal" id="about" aria-labelledby="about-title">
    <p className="eyebrow">〈 What I did 〉</p>
    <h2 id="about-title">Project Scope</h2>
    <p className="project-technologies"><strong>사용 기술</strong><br />{pulmuoneProject.technologies}</p>
    <p className="section-lead">풀무원 메인페이지를 공동 작업하고,<br />바른먹거리 하위 5개 페이지의 구조 설계와<br />UI 구현을 담당했습니다.</p>
    <div className="overview-grid" aria-label="프로젝트 개요"><div className="overview-item"><small>PROJECT</small><strong>풀무원 웹 리뉴얼</strong><span>팀 프로젝트 · 2026.07.21—08.14</span></div><div className="overview-item"><small>MY ROLE</small><strong>하위 5개 페이지</strong><span>콘텐츠 구조 설계 · UI 구현</span></div><div className="overview-item"><small>COLLABORATION</small><strong>메인 공동 작업</strong><span>공통 경험과 인터랙션 연결</span></div><div className="overview-item"><small>OUTPUT</small><strong>총 6개 화면</strong><span>반응형 웹 · 접근성 · 성능 검증</span></div></div>
  </section>
  <section className="scope" id="scope" aria-labelledby="scope-title">
    <div className="wrap scope-head reveal"><p className="eyebrow">〈 My Scope 〉</p><h2 className="section-title" id="scope-title">Capabilities</h2><p className="section-lead">보이는 화면뿐 아니라 재사용 가능한 규칙, 접근 가능한 동작, 측정 가능한 성능까지 구현 범위에 포함했습니다.</p></div>
    <div className="accordion wrap">
      <details open><summary><span className="accordion-title"><small>01 / STRUCTURE</small><strong>콘텐츠 구조 설계</strong></span><span className="accordion-outcome">5개 페이지 흐름</span></summary><div className="accordion-content"><div><strong className="info-label">핵심 작업</strong><p>복잡한 정책과 캠페인 정보를 사용자가 순서대로 이해할 수 있도록 섹션, 카드, 정보 위계로 재구성했습니다.</p></div><div><strong className="info-label">구현 결과</strong><p>지속가능 식생활·식품·바른먹거리 원칙·캠페인·품질정책의 목적에 맞춘 5개의 서로 다른 페이지 흐름을 완성했습니다.</p><div className="scope-evidence" aria-label="콘텐츠 구조 설계 증거"><a href="https://www.figma.com/design/HnAjMMnz0uICf9f3XMz8De/%ED%92%80%EB%AC%B4%EC%9B%90---%EB%94%94%EC%9E%90%EC%9D%B8%EC%8B%9C%EC%95%88?node-id=406-35" target="_blank" rel="noopener">Figma 시안 ↗</a><a href="https://github.com/icerence/kiwik-project" target="_blank" rel="noopener">GitHub 구현 코드 ↗</a></div></div></div></details>
      <details><summary><span className="accordion-title"><small>02 / UI</small><strong>Figma to Responsive UI</strong></span><span className="accordion-outcome">Desktop + Mobile</span></summary><div className="accordion-content"><div><strong className="info-label">핵심 작업</strong><p>Figma 시안을 HTML5, CSS, Vanilla JavaScript로 옮기고 화면 크기가 달라도 콘텐츠 우선순위가 유지되도록 구현했습니다.</p></div><div><strong className="info-label">구현 결과</strong><p>데스크톱·모바일 반응형 화면과 스크롤·클릭·키보드 입력을 지원하는 내비게이션 상태를 연결했습니다.</p><div className="scope-evidence" aria-label="반응형 UI 증거"><a href="https://www.figma.com/design/HnAjMMnz0uICf9f3XMz8De/%ED%92%80%EB%AC%B4%EC%9B%90---%EB%94%94%EC%9E%90%EC%9D%B8%EC%8B%9C%EC%95%88?node-id=406-35" target="_blank" rel="noopener">반응형 Figma 시안 ↗</a><a href="https://icerence.github.io/kiwik-project/" target="_blank" rel="noopener">배포 화면 ↗</a></div></div></div></details>
      <details><summary><span className="accordion-title"><small>03 / SYSTEM</small><strong>디자인 시스템</strong></span><span className="accordion-outcome">145 Tokens</span></summary><div className="accordion-content"><div><strong className="info-label">핵심 작업</strong><p>색상·간격·크기·상태를 이름 있는 토큰으로 정의하고 공통 헤더·푸터·컴포넌트가 같은 규칙을 사용하도록 구성했습니다.</p></div><div><strong className="info-label">구현 결과</strong><p>메인 변수 132개와 공통 색상 13개, 총 145개 토큰 및 4단계 구현 절차와 하드코딩 자동 검사를 남겼습니다.</p><div className="scope-evidence" aria-label="디자인 시스템 증거"><a href="https://www.figma.com/design/ePhLkt6OzxLw9p38nOcvrx/kiwik_design_system" target="_blank" rel="noopener">Figma 디자인 시스템 ↗</a><a href="evidence/design-system-harness.md">구현 기준 문서 ↗</a></div></div></div></details>
      <details><summary><span className="accordion-title"><small>04 / QUALITY</small><strong>성능·접근성 검증</strong></span><span className="accordion-outcome">94% Lighter</span></summary><div className="accordion-content"><div><strong className="info-label">핵심 작업</strong><p>W3C, ESLint, Lighthouse 결과에서 실제 문제를 분리해<br />이미지, 로딩 순서, ARIA, 메뉴 상태 오류를 수정했습니다.</p></div><div><strong className="info-label">구현 결과</strong><p>25개 PNG를 WebP로 변환하고 크기 명시와<br />지연 로딩을 적용해 이미지 총용량을 약 94% 줄였습니다.</p><div className="scope-evidence" aria-label="성능과 접근성 검증 증거"><a href="reports/%EB%B0%94%EB%A5%B8%EB%A8%B9%EA%B1%B0%EB%A6%AC-%EC%84%B1%EB%8A%A5-%EA%B0%9C%EC%84%A0-%EB%B3%B4%EA%B3%A0%EC%84%9C-2026-08-13.html">성능 개선 보고서 ↗</a><a href="https://github.com/icerence/kiwik-project/tree/main/docs" target="_blank" rel="noopener">검사 자료 ↗</a></div></div></div></details>
      <details><summary><span className="accordion-title"><small>05 / WORKFLOW</small><strong>AI 협업 자동화</strong></span><span className="accordion-outcome">Reusable Workflow</span></summary><div className="accordion-content"><div><strong className="info-label">핵심 작업</strong><p>업무별 스킬과 에이전트 역할을 분리하고<br />생성 결과를 반복 검토하는 작업 절차를 구성했습니다.</p></div><div><strong className="info-label">구현 결과</strong><p>FigJam 변경 내용을 작성자·업무 유형별로 구조화해<br />Notion 회의록으로 옮기는 재현 가능한 자동화 흐름을 설계했습니다.</p><div className="scope-evidence" aria-label="AI 협업 자동화 증거"><a href="evidence/figjam-notion-workflow.md">자동화 절차 ↗</a><a href="https://www.figma.com/board/tTNn7XY4aHoeSO7p1fTaWX/%ED%82%A4%EC%9C%85-%ED%9A%8C%EC%9D%98%EB%B3%B4%EB%93%9C" target="_blank" rel="noopener">FigJam 원본 ↗</a><a href="https://app.notion.com/p/123566c2471d82c89423017b9d966342?v=58a566c2471d837cafed889ad635aae2" target="_blank" rel="noopener">Notion 결과 ↗</a></div></div></div></details>
    </div>
  </section>
  <section className="evidence wrap" id="evidence" aria-labelledby="evidence-title">
    <div className="evidence-head reveal"><p className="eyebrow">〈 Evidence 〉</p><h2 id="evidence-title">말보다<br />작동하는 증거</h2><p className="section-lead">성과 수치가 아니라 직접 열어보고 재사용할 수 있는 구현 자료를 모았습니다.</p></div>
    <div className="evidence-grid"><article className="evidence-card reveal"><strong className="evidence-stat">Tokens</strong><h3>디자인 토큰 파일</h3><p>색상·간격·크기를 이름 있는 규칙으로 관리하는 공통 토큰 원본입니다.</p><a className="evidence-link" href="assets/css/food-tokens.css">토큰 파일 열기 ↗</a></article><article className="evidence-card reveal"><strong className="evidence-stat">Component</strong><h3>Dot Navigation</h3><p>현재 섹션의 위치를 알려주고,<br />원하는 섹션으로 빠르게 이동할 수 있는 재사용 컴포넌트입니다.</p><a className="evidence-link" href="https://icerence.github.io/kiwik-project/" target="_blank" rel="noopener">적용 화면 보기 ↗</a></article><article className="evidence-card reveal"><strong className="evidence-stat">Harness</strong><h3>구현 기준 문서</h3><p>Clarify → Reuse → Implement → Evaluate 순서와 품질 기준을 기록했습니다.</p><a className="evidence-link" href="evidence/design-system-harness.md">문서 열기 ↗</a></article><article className="evidence-card reveal"><strong className="evidence-stat">Guardrail</strong><h3>하드코딩 자동 검사</h3><p>색상 원시값과 허용되지 않은 패턴을<br />편집 단계에서 탐지하는 실행 코드입니다.</p><a className="evidence-link" href="evidence/hooks/check-hardcode.fixed.mjs">검사 코드 열기 ↗</a></article><article className="evidence-card reveal"><strong className="evidence-stat">Workflow</strong><h3>자동 회의록 절차</h3><p>FigJam 변경 내용을 작성자와 업무 유형별로 분류해<br />Notion에 반영하는 재사용 절차입니다.</p><a className="evidence-link" href="evidence/figjam-notion-workflow.md">절차 문서 열기 ↗</a></article></div>
  </section>
  <div className="ribbon" aria-hidden="true"><div className="ribbon-line"><div className="ribbon-track"><span>145 TOKENS ← 25 IMAGES → 6 PAGES ← 94% LIGHTER →</span><span>145 TOKENS ← 25 IMAGES → 6 PAGES ← 94% LIGHTER →</span></div></div><div className="ribbon-line"><div className="ribbon-track"><span>DESIGN → SYSTEM → IMPLEMENT → VERIFY →</span><span>DESIGN → SYSTEM → IMPLEMENT → VERIFY →</span></div></div></div>
  <section className="metrics wrap" aria-labelledby="metrics-title">
    <div className="metrics-head reveal"><div><p className="eyebrow">〈 Measured Results 〉</p><h2 className="section-title" id="metrics-title">Results</h2></div><p className="section-lead">성과는 장식용 숫자가 아니라<br />동일 조건의 Lighthouse 측정과<br />저장된 보고서를 기준으로 기록했습니다.</p></div>
    <div className="metrics-grid">
      <article className="metric-card reveal"><strong className="metric-value">6 Pages</strong><h3>페이지 구현</h3><p>풀무원 메인 1개 + 바른먹거리 하위 5개</p></article>
      <article className="metric-card reveal"><strong className="metric-value">145</strong><h3>디자인 토큰</h3><p>메인 변수 132개 + 공통 색상 토큰 13개</p></article>
      <article className="metric-card reveal"><strong className="metric-value">94%↓</strong><h3>이미지 용량 절감</h3><p>약 34.8MiB에서 약 2.0MiB로 최적화</p></article>
      <article className="metric-card reveal"><strong className="metric-value"><span className="before">27.0s</span><span className="change">→</span>9.8s</strong><h3>모바일 평균 LCP</h3><p>바른먹거리 하위 5개 페이지 동일 조건 측정</p></article>
      <article className="metric-card reveal"><strong className="metric-value"><span className="before">72</span><span className="change">→</span>95</strong><h3>데스크톱 성능</h3><p>지속가능 식생활 페이지 Lighthouse 결과</p></article>
      <article className="metric-card reveal"><strong className="metric-value">All 100</strong><h3>SEO</h3><p>최적화 후 바른먹거리 하위 5개 페이지</p></article>
    </div>
  </section>
  <section className="process wrap" id="process" aria-labelledby="process-title">
    <div className="process-head reveal"><p className="eyebrow">〈 Problem Solving 〉</p><h2 id="process-title">문제 해결에서<br />품질 향상까지</h2></div>
    <div className="comparison-grid" aria-label="개선 전후 비교"><article className="comparison-card reveal"><h3>이미지 용량</h3><div className="comparison-bars"><div className="comparison-row"><span>Before</span><i className="comparison-track"><b className="comparison-fill" style={{'--value':'100%'}} /></i><strong>34.8MiB</strong></div><div className="comparison-row after"><span>After</span><i className="comparison-track"><b className="comparison-fill" style={{'--value':'6%'}} /></i><strong>2.0MiB</strong></div></div><p className="comparison-caption">WebP 변환과 표시 크기 기준 리사이징으로 전체 이미지 용량을 94% 줄였습니다.</p></article><article className="comparison-card reveal"><h3>Lighthouse 성능</h3><div className="comparison-bars"><div className="comparison-row"><span>Before</span><i className="comparison-track"><b className="comparison-fill" style={{'--value':'72%'}} /></i><strong>72점</strong></div><div className="comparison-row after"><span>After</span><i className="comparison-track"><b className="comparison-fill" style={{'--value':'95%'}} /></i><strong>95점</strong></div></div><p className="comparison-caption">지속가능 식생활 페이지의 데스크톱 동일 조건 측정 결과입니다.</p></article></div>
    <div className="steps">
      <article className="step"><span className="step-number">01 / System</span><h3>디자인 시스템 재구축</h3><div className="step-detail"><p><strong>문제</strong>초기 구조를 충분히 이해하지 못해 페이지 제작을 다시 시작해야 했습니다.</p><p><strong>해결</strong>토큰 참조 구조를 다시 학습하고 하네스와 자동 검사까지 포함해 재구축했습니다.</p><p className="step-result"><strong>결과</strong><span>토큰·구현·검증 기준을 하나의 작업 체계로 연결</span></p></div></article>
      <article className="step"><span className="step-number">02 / Consistency</span><h3>공통 영역 일괄 적용</h3><div className="step-detail"><p><strong>문제</strong>페이지마다 헤더·head·푸터가 달라 수정 누락과 동작 차이가 발생했습니다.</p><p><strong>해결</strong>공통 원본과 동기화 도구를 구성해 같은 구조와 설정을 사용하도록 통일했습니다.</p><p className="step-result"><strong>결과</strong><span>한 번의 수정으로 6개 페이지 공통 영역을 동일하게 반영</span></p></div></article>
      <article className="step"><span className="step-number">03 / Verification</span><h3>생성 결과 품질 검증</h3><div className="step-detail"><p><strong>문제</strong>생성 결과가 화면 목적과 구현 기준을 안정적으로 충족하는지 판단할 공통 기준이 필요했습니다.</p><p><strong>해결</strong>반응형·접근성·성능 기준으로 직접 검토하고, 통과하지 못한 결과는 코드와 에셋을 수정했습니다.</p><p className="step-result"><strong>결과</strong><span>도구와 관계없이 최종 품질을 직접 판단하고 책임지는 검증 흐름 확립</span></p></div></article>
    </div>
  </section>
  <section className="closing" aria-labelledby="closing-title"><div className="wrap reveal"><p className="eyebrow">〈 Epilogue 〉</p><h2 id="closing-title">풀무원 프로젝트를 하며</h2><p className="closing-copy closing-reflection">처음에는 AI를 활용하면 페이지를 쉽게 만들 수 있을 줄 알았습니다.<br />하지만 구조를 잘 모르는 상태에서 작업하다 보니, 만든 것을 처음부터 다시 만드는 일도 있었습니다.<br />그 일을 계기로 결과만 보기보다 왜 이렇게 만들어지는지 이해하려고 했고<br />그로 인해 더욱 완성도 높게 프로젝트를 만들 수 있었습니다.</p><p className="closing-copy closing-reflection">배운 내용을 직접 적용해서 우리 팀의 페이지가 완성되는 과정이 재미있었고,<br />막히던 문제를 하나씩 해결하면서 다음에는 더 잘 만들 수 있겠다는 자신감도 생겼습니다.</p><p className="closing-copy">끝까지 봐주셔서 감사합니다.</p></div></section>
</main>
)}
