import { useEffect, useState } from 'react';
import HomePage from './pages/HomePage.jsx';
import PulmuonePage from './pages/PulmuonePage.jsx';

const EMAIL='dongkyunpeter@gmail.com';
const GMAIL=`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(EMAIL)}`;

function Header({isHome}){
  const [menuOpen,setMenuOpen]=useState(false); const [projectsOpen,setProjectsOpen]=useState(false); const [scrolled,setScrolled]=useState(false); const [hidden,setHidden]=useState(false);
  useEffect(()=>{let last=scrollY;const onScroll=()=>{const y=scrollY;setScrolled(y>90);setHidden(y>last&&y>260);last=y};const onKey=event=>{if(event.key==='Escape'){setProjectsOpen(false);setMenuOpen(false)}};addEventListener('scroll',onScroll,{passive:true});addEventListener('keydown',onKey);return()=>{removeEventListener('scroll',onScroll);removeEventListener('keydown',onKey)}},[]);
  const home=isHome?'':'index.html'; const close=()=>{setMenuOpen(false);setProjectsOpen(false)};
  return <header className={`site-header common-header${scrolled?' is-scrolled':''}${hidden?' is-hidden':''}`}><div className="wrap common-header-inner"><a className="logo common-logo" href={isHome?'#top':'index.html'} aria-label="강동균 포트폴리오 메인으로 이동">KDK</a><nav className={`nav common-nav${menuOpen?' open':''}`} id="nav" aria-label="주요 메뉴"><a href={`${home}#profile`} onClick={close}>Profile</a><div className={`common-nav-group${projectsOpen?' is-open':''}`}><button className={`common-nav-trigger${isHome?'':' is-current'}`} type="button" aria-expanded={projectsOpen} aria-controls="project-subnav" onClick={()=>setProjectsOpen(value=>!value)}>Projects <span aria-hidden="true">▾</span></button><div className="common-subnav" id="project-subnav"><a href="pulmuone.html" aria-current={isHome?undefined:'page'}><strong>풀무원 웹 리뉴얼</strong><small>Team Project · Published</small></a><span aria-disabled="true"><strong>다음 프로젝트</strong><small>Personal Project · Coming Soon</small></span><span aria-disabled="true"><strong>프로젝트 추가 예정</strong><small>Web Project · Coming Soon</small></span></div></div><a href="#contact" onClick={close}>Contact</a></nav><div className="header-actions common-actions"><a className="pill" href={GMAIL} target="_blank" rel="noreferrer">Email ↗</a><a className="pill dark" href="https://github.com/dongkyunpeter-alt/kdk_portfolio" target="_blank" rel="noreferrer">GitHub ↗</a></div><button className="menu menu-button common-menu" id="menu" type="button" aria-controls="nav" aria-expanded={menuOpen} onClick={()=>setMenuOpen(value=>!value)}><span data-menu-label>{menuOpen?'Close':'Menu'}</span> ☰</button></div></header>;
}

function Footer({isHome}){
  const home=isHome?'':'index.html'; const [copied,setCopied]=useState(false); const copy=async()=>{try{await navigator.clipboard.writeText(EMAIL)}catch{}setCopied(true);setTimeout(()=>setCopied(false),1600)};
  return <footer className="footer common-footer" id="contact"><div className="wrap"><div className="common-footer-grid"><div><h2>다음 화면을 함께<br/>구현할 준비가 되어 있습니다.</h2><a className="pill dark" href={GMAIL} target="_blank" rel="noreferrer">Email 보내기 ↗</a></div><div><h3>PORTFOLIO</h3><ul><li><a href={`${home}#profile`}>Profile</a></li><li><a href={`${home}#projects`}>Projects</a></li></ul></div><div><h3>CONTACT</h3><p className="common-email-row"><a href={GMAIL} target="_blank" rel="noreferrer">{EMAIL}</a><button className="common-copy-email" type="button" aria-label="이메일 주소 복사" onClick={copy}>{copied?'복사됨':'복사'}</button></p><p><a href="https://github.com/dongkyunpeter-alt/kdk_portfolio" target="_blank" rel="noreferrer">GitHub ↗</a></p></div></div><div className="common-copyright"><span>© 2026 Kang Donggyun. All rights reserved.</span><span>Web Publishing · Responsive UI · Design System</span></div></div></footer>;
}

function usePageEffects(isHome){useEffect(()=>{document.title=isHome?'강동균 — Web Portfolio':'풀무원 웹 리뉴얼 — 강동균 포트폴리오';document.documentElement.classList.add('motion-ready');if(isHome)return;const nodes=[...document.querySelectorAll('.reveal,.section-title,.intro h2,.process-head h2,.closing h2')];nodes.forEach(node=>{if(node.matches('.section-title,.intro h2,.process-head h2,.closing h2'))node.classList.add('text-reveal')});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});nodes.forEach(node=>observer.observe(node));return()=>observer.disconnect()},[isHome])}

export default function App(){const isHome=!location.pathname.endsWith('/pulmuone.html');const [showTop,setShowTop]=useState(false);usePageEffects(isHome);useEffect(()=>{if(isHome)return;const handler=()=>setShowTop(scrollY>420);addEventListener('scroll',handler,{passive:true});return()=>removeEventListener('scroll',handler)},[isHome]);return <><a className="skip" href="#main">본문으로 건너뛰기</a><Header isHome={isHome}/>{isHome?<HomePage/>:<PulmuonePage/>}{!isHome&&<button id="back-to-top" className={`back-to-top${showTop?' show':''}`} type="button" aria-label="맨 위로 이동" onClick={()=>scrollTo({top:0,behavior:'smooth'})}>↑</button>}<Footer isHome={isHome}/></>}
